name: Create Signed Tag Manually

on:
  workflow_dispatch: 
    branches: master
    inputs:
      tag_name:
        description: 'Tag name to create'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.WEBSITE_SECRET_PAT }}

    - name: Check Tag Name
      id: check_tag_name
      if: ${{ github.event.inputs.tag_name != '' }}
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ github.event.inputs.tag_name }}
        regex: '^\d+\.\d+\.\d+$'
      

    - name: GPG Import
      if: ${{ steps.check_tag_name.outputs.match != '' }}
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.SIGNING_BONUS_TAGS }}
        passphrase: ${{ secrets.SIGNING_BONUS_PHRASE }}
        git-user-signingkey: true
        git-tag-gpgsign: true

    - name: Sign and Push Tag
      if: ${{ steps.check_tag_name.outputs.match != '' }}
      run: |
        git tag -s ${{ github.event.inputs.tag_name }} -m 'Tag for Sigil-${{ github.event.inputs.tag_name }} release'
        git push origin ${{ github.event.inputs.tag_name }}
        gpg --detach-sign --pinentry-mode loopback --passphrase ${{ secrets.SIGNING_BONUS_PHRASE }} version.xml
        git archive --prefix=${$(basename $(pwd))}-${steps.check_tag_name.outputs.match#v}/ -o ${$(basename $(pwd))}-${steps.check_tag_name.outputs.match#v}.tar.gz ${steps.check_tag_name.outputs.match}
