name: Create Signed Tag

on:
  push:
    branches: [ master ]
    tags-ignore:
      - '**'
    paths-ignore:
    - 'docs/**'
    - 'installer/win_installer_note.txt'
    - 'ChangeLog.txt'
    - 'COPYING.txt'
    - 'version.xml'
    - '.retired_travis.yml'
    - '**/**.md'

  pull_request:
    branches: [ master ]
    tags-ignore:
      - '**'
    paths-ignore:
    - 'docs/**'
    - 'installer/win_installer_note.txt'
    - 'ChangeLog.txt'
    - 'COPYING.txt'
    - 'version.xml'
    - '.retired_travis.yml'
    - '**/**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Tag Name
      id: get_tag_name
      if: "contains(github.event.head_commit.message, '[tag:') && github.event_name != 'pull_request'"
      run: |
        msg="${{ github.event.head_commit.message }}"
        echo ::set-output name=tag_name::${echo "$msg" | sed -e 's/\[tag:.*(\d+\.\d+\.\d+).*/$1/g'}

    - name: Show Tag Name
      run: |
        echo ${{ steps.get_tag_name.outputs.tag_name }}