name: Make Blog Post

on:
  release:
    types: published

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: main

      - name: Checkout website
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WEBSITE_SECRET_PAT }}
          repository: dougmassay/dougmassay.github.io
          ref: ${{ github.head_ref }}
          path: website

      - name: Get Release details
        run: |
          pip install python-dateutil
          echo '{"tag_name": "${{ github.event.release.tag_name }}",' > details.txt
          echo '"release_name": "${{ github.event.release.name }}",' >> details.txt
          echo '"published_date": "${{ github.event.release.published_at }}"}' >> details.txt
          echo "${{ github.event.release.body }}" > contents.txt
          echo "$GITHUB_WORKSPACE/main"
          echo "$GITHUB_WORKSPACE/website"
          python $GITHUB_WORKSPACE/main/.github/workflows/make_post.py -p $GITHUB_WORKSPACE
          mv ./*.md $GITHUB_WORKSPACE/website/_posts

      - name: Commit post to blog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: website
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
          commit_message: Auto create release blog post
          branch: master

  
