name: Make Blog Post

on:
  release:
    types: [published, edited]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: dougmassay/dougmassay.github.io
          ref: master

      - name: Get Release details
        run: |
          pip install dateutil
          echo '{"tag_name": "${{ github.event.release.tag_name }}",' > details.txt
          echo '"release_name": "${{ github.event.release.name }}",' >> details.txt
          echo '"published_date": "${{ github.event.release.published_at }}"}' >> details.txt
          echo ${{ github.event.release.body }}" > contents.txt
          python make_post.py -p $GITHUB_WORKSPACE
          rm details.txt
          rm body.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>
          commit_message: Auto create release blog post
          branch: master

  
