name: Make Blog Post

on:
  release:
    types: [published, edited]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release details
        run: |
          echo "Tag name: ${{ github.event.release.tag_name }}"
          echo "Release: ${{ github.event.release.description }}"
          echo "Body: ${{ github.event.release.body }}"
  
